# Generated by Django 3.2 on 2021-05-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iphoneapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='image',
        ),
    ]
