# Generated by Django 3.2 on 2021-05-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iphoneapp', '0002_remove_store_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='imagefile',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
