# Generated by Django 3.2 on 2021-05-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iphoneapp', '0003_store_imagefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.AutoField(primary_key=True, serialize=False)),
                ('custemail', models.CharField(max_length=50)),
                ('storeid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('totalprice', models.FloatField(max_length=50)),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.AlterField(
            model_name='store',
            name='imagefile',
            field=models.FileField(blank='True', null=True, upload_to='media/'),
        ),
    ]
