# Generated by Django 3.2 on 2021-05-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iphoneapp', '0004_auto_20210518_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='custemail',
            new_name='custemailid',
        ),
    ]
