# Generated by Django 3.2 on 2021-05-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iphoneapp', '0005_rename_custemail_cart_custemailid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('custemail', models.CharField(max_length=50)),
                ('orderdate', models.CharField(max_length=50)),
                ('totalbill', models.FloatField(max_length=50)),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
    ]
