# Generated by Django 3.2 on 2021-05-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iphoneapp', '0006_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='custemail',
            new_name='custemailid',
        ),
    ]
